name: Build MCC and Documents

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
env:
  PROJECT: "MinecraftClient"
  target-version: "net7.0"
  compile-flags: "--self-contained=true -c Release -p:UseAppHost=true -p:IncludeNativeLibrariesForSelfExtract=true -p:EnableCompressionInSingleFile=true -p:DebugType=None"

jobs:
  build-only:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    timeout-minutes: 15
    strategy:
      matrix:
        target: [win-x86, win-x64, win-arm, win-arm64, linux-x64, linux-arm, linux-arm64, osx-x64, osx-arm64]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: 'true'

    - name: Setup Project Path
      run: |
        echo project-path=${{ github.workspace }}/${{ env.PROJECT }} >> $GITHUB_ENV
        
    - name: Setup Output Paths
      run: |
        echo target-out-path=${{ env.project-path }}/bin/Release/${{ env.target-version }}/${{ matrix.target }}/publish/ >> $GITHUB_ENV

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2.1.0

    - name: Get Version DateTime
      id: date-version
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: 0
        format: 'YYYY-MM-DD'

    - name: VersionInfo
      run: |
        COMMIT=$(echo ${{ github.sha }} | cut -c 1-7)
        echo '' >> ${{ env.project-path }}/Properties/AssemblyInfo.cs
        echo build-version-info=${{ steps.date-version.outputs.time }}-${{ github.run_number }} >> $GITHUB_ENV
        echo "[assembly: AssemblyConfiguration(\"GitHub build ${{ github.run_number }}, built on ${{ steps.date-version.outputs.time }} from commit $COMMIT\")]" >> ${{ env.project-path }}/Properties/AssemblyInfo.cs

    - name: Build Target
      run: dotnet publish ${{ env.project-path }}.sln -f ${{ env.target-version }} -r ${{ matrix.target }} ${{ env.compile-flags }}
      
    - name: Zip Target
      run: zip -qq -r windows-x86.zip *
      working-directory: ${{ env.target-out-path }}

    - name: Get Release DateTime
      id: date-release
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: 0
        format: 'YYYYMMDD'

    - name: Target Publish Executable
      uses: tix-factory/release-manager@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        mode: uploadReleaseAsset
        filePath: ${{ env.target-out-path }}${{ env.PROJECT }} ${{ (startsWith('win', matrix.target) && '.exe') || '' }}
        assetName: ${{ env.PROJECT }}-${{ env.build-version-info }}-${{ matrix.target }}.exe
        tag: ${{ format('{0}-{1}', steps.date-release.outputs.time, github.run_number) }}
